## makefile automates the build and deployment for python projects


## build config

# type of project
PROJ_TYPE =		cl
# make modules to add functionality to a build
PROJ_MODULES =		git
INFO_TARGETS +=		appinfo
# additional resources generated by the build that should be cleaned up
#ADD_CLEAN +=


## project specific

# add run command line arguments
CL_RUN_ARGS +=		run tests/test.json

# entry application
CL_PROTO_APP = 		./jsonl.ros

# edit these if you want
#GITUSER =		johndoe


## targets

include ./zenbuild/main.mk

.PHONY:			appinfo
appinfo:
			@echo "run-arguments: $(CL_RUN_ARGS)"

.PHONY:			testall
testall:		test run
